name: Dynamic Portfolio
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
title: Mikko Oikkonen
description: Dynaaminen Portfolio
url: "https://mikkoo.me"
baseurl: "/"

collections:
  - jobs
  - projects
  - feats
