name: Dynamic Portfolio
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
title: Mikko Oikkonen
description: Dynaaminen Portfolio
url: "https://miukkonen.github.io/portfolio23"   #https://mikkoo.me" # "https://mmoi.github.io/mikkoo"
baseurl: "/" # "/"

#exclude: [sass]

collections:
  - jobs
  - projects
  - feats

